### ISSUE TITLE
setuptools support

### ISSUE THREAD

**Issue by Ichunjo** [HolyWu/vs-ffdnet#2]
Hello,

can you add a setup.py file, please? 
This would greatly facilitate the installation

**Comment by HolyWu** [comment]
Sorry, never learned setuptools. Need some time to study it. Any tutorial recommended?

**Comment by Ichunjo** [comment]
This one helped me:
https://packaging.python.org/tutorials/packaging-projects/#configuring-metadata
You don't have to specify all the arguments.

Alternatively, you can see real examples here:
https://github.com/Irrational-Encoding-Wizardry/lvsfunc/blob/master/setup.py
https://github.com/Irrational-Encoding-Wizardry/vs-debandshit/blob/master/setup.py
https://github.com/Ichunjo/vardefunc/blob/master/setup.py

They're mostly useful for Pypi package but also useful to install directly from github with the following command:
```
python -m pip install git+https://github.com/Ichunjo/vardefunc.git
```
For vsffdnet, it would be:
```
python -m pip install git+https://github.com/HolyWu/vs-ffdnet.git
```

**Comment by HolyWu** [comment]
Thanks for the information!
